### ISSUE TITLE
save_handler timer is confusing

### ISSUE THREAD

**Issue by mscbg** [ZigzagAK/ngx_http_upsync_upstream#1]
Hi，ZigzagAK：
Your ngx_http_upsync_upstream module is realy cool and it is very useful for me. I have read your code and got a question. 'ngx_add_timer' is used in 'ngx_http_upsync_save_handler' when sync_upstreams failed. Is this for unresolved servers? If sync_upstreams always failed(no mem or state_open failed), timer handler will run again and again.  'ngx_http_upsync_sync_upstream_ready' will also set a timer, so number of timer will be bigger and bigger and can never be expired. I don't know whether I did't understand your meaning.

**Comment by ZigzagAK** [comment]
@mscbg 
Hi!
ngx_add_timer function check for the timer already set. If timer already set, existing timer object will be deleted from timer tree and added with new expiration time.

```
static ngx_inline void
ngx_event_add_timer(ngx_event_t *ev, ngx_msec_t timer)
{
    ngx_msec_t      key;
    ngx_msec_int_t  diff;

    key = ngx_current_msec + timer;

    if (ev->timer_set) {

        /*
         * Use a previous timer value if difference between it and a new
         * value is less than NGX_TIMER_LAZY_DELAY milliseconds: this allows
         * to minimize the rbtree operations for fast connections.
         */

        diff = (ngx_msec_int_t) (key - ev->timer.key);

        if (ngx_abs(diff) < NGX_TIMER_LAZY_DELAY) {
            ngx_log_debug3(NGX_LOG_DEBUG_EVENT, ev->log, 0,
                           "event timer: %d, old: %M, new: %M",
                            ngx_event_ident(ev->data), ev->timer.key, key);
            return;
        }

        ngx_del_timer(ev);
    }

    ev->timer.key = key;

    ngx_log_debug3(NGX_LOG_DEBUG_EVENT, ev->log, 0,
                   "event timer add: %d: %M:%M",
                    ngx_event_ident(ev->data), timer, ev->timer.key);

    ngx_rbtree_insert(&ngx_event_timer_rbtree, &ev->timer);

    ev->timer_set = 1;
}
```

**Comment by mscbg** [comment]
@ZigzagAK .Thanks for your reply. And I know ngx_add_timer will not add an exist timer. My question is when 'ngx_http_upsync_upstream_save' return is not EDPVS_OK, timer will be added again. For examle, a timer is set in 'ngx_http_upsync_sync_upstream_ready' and ngx_http_upsync_save_handler will be called. If 'ngx_http_upsync_upstream_save' can not return EDPVS_OK，timer will be added again. I think this is mean a timer will always be exist. If 'ngx_http_upsync_sync_upstream_ready' is called 10000 times, timer will be 10000 in nginx and could not be expired. If  'ngx_http_upsync_upstream_save' return  EDPVS_OK, there will be no problem.

**Comment by ZigzagAK** [comment]
No 10000 timeas will be created.
ngx_add_timer(&hscf->ev, 5000);
Only one instance of ngx_event_t per upstream is used and any ngx_time_add call uses this instance of ngx_event_t. ngx_http_upsync_upstream_save handled with hscf->ev.

**Comment by mscbg** [comment]
O, Yes. Thanks a lot! ^_^
